# This is a working example.
# For a more complete reference use `--example`
kibot:
  version: 1

global:
  dir: output

import:
- file: JLCPCB
  definitions:
    _KIBOT_MANF_DIR: +/Manufacturers/JLCPCB
    _KIBOT_POS_PRE_TRANSFORM: '[''_kicost_rename'', ''_rot_footprint'']'
    _KIBOT_BOM_ENABLED: 'false'

preflight:
  fill_zones: true
  run_drc: true
  run_erc: false
  filters:
    - filter: 'ignore no courtyard'
      error: 'missing_courtyard'
    - filter: 'ignore silkscreem edge clearance'
      error: 'silk_edge_clearance'

outputs:
- name: basic_ibom
  comment: Interactive HTML BoM
  type: ibom
  dir: +/Assembly
  options:
    layer_view: F
    highlight_pin1: true
    sort_order: R,D,C,L,U,Y,X,F,SW,A,~,HS,CNN,J,P,NT,MH
- name: basic_boardview
  comment: Board View export
  type: boardview
  dir: +/Assembly
- name: generic_bom_html
  comment: Generic Bill of Materials in HTML format
  type: bom
  dir: +/BoM
  options:
    format: HTML
    count_smd_tht: true
- name: generic_bom_csv
  comment: Generic Bill of Materials in CSV format
  type: bom
  dir: +/BoM
  options:
    format: CSV
    count_smd_tht: true
- name: generic_bom_xlsx
  comment: Generic Bill of Materials in XLSX format
  type: bom
  dir: +/BoM
  options:
    format: XLSX
    count_smd_tht: true
- name: basic_diff_pcb
  comment: PCB diff between the last two changes
  type: diff
  dir: +/diff
  options:
    old: KIBOT_LAST-1
    old_type: git
    new: HEAD
    new_type: git
    cache_dir: .cache
    add_link_id: true
- name: basic_diff_sch
  comment: Schematic diff between the last two changes
  type: diff
  dir: +/diff
  options:
    old: KIBOT_LAST-1
    old_type: git
    new: HEAD
    new_type: git
    cache_dir: .cache
    add_link_id: true
    pcb: false
#- name: basic_gerb_drill
#  comment: Drill files in GERB_DRILL format
#  type: gerb_drill
#  dir: +/Gerbers_and_Drill
#  options:
#    map: gerber
#- name: gerber_modern
#  comment: Gerbers in modern format, recommended by the standard
#  type: gerber
#  dir: +/Gerbers_and_Drill
#  layers:
#  - layer: F.Cu
#    suffix: F_Cu
#    description: Front copper
#  - layer: In1.Cu
#    suffix: In1_Cu
#    description: Inner layer 1
#  - layer: In2.Cu
#    suffix: In2_Cu
#    description: Inner layer 2
#  - layer: B.Cu
#    suffix: B_Cu
#    description: Bottom copper
#  - layer: B.Silkscreen
#    suffix: B_Silkscreen
#    description: Bottom silkscreen (artwork)
#  - layer: F.Silkscreen
#    suffix: F_Silkscreen
#    description: Front silkscreen (artwork)
#  - layer: B.Mask
#    suffix: B_Mask
#    description: Bottom soldermask (negative)
#  - layer: F.Mask
#    suffix: F_Mask
#    description: Front soldermask (negative)
#  - layer: User.Drawings
#    suffix: User_Drawings
#    description: User drawings
#  - layer: User.Comments
#    suffix: User_Comments
#    description: User comments
#  - layer: Edge.Cuts
#    suffix: Edge_Cuts
#    description: Board shape
#  - layer: B.Courtyard
#    suffix: B_Courtyard
#    description: Bottom courtyard area
#  - layer: F.Courtyard
#    suffix: F_Courtyard
#    description: Front courtyard area
#  - layer: F.Fab
#    suffix: F_Fab
#    description: Front documentation
- name: basic_info
  comment: Information about the run
  type: info
  dir: +/.
- name: basic_pcbdraw_png_top
  comment: PCB 2D render in PNG format - top
  type: pcbdraw
  dir: +/PCB
  options:
    style:
      board: '#6b3b84'
      copper: '#9a24db'
      pads: '#bfba9e'
    format: png
- name: basic_pcbdraw_png_bottom
  comment: PCB 2D render in PNG format - bottom
  type: pcbdraw
  dir: +/PCB
  options:
    style:
      board: '#6b3b84'
      copper: '#9a24db'
      pads: '#bfba9e'
    format: png
    bottom: true
- name: basic_pdf_sch_print
  comment: Schematic in PDF format
  type: pdf_sch_print
  dir: +/Schematic
- name: basic_svg_sch_print
  comment: Schematic in SVG format
  type: svg_sch_print
  dir: +/Schematic
#- name: basic_render_3d_top
#  comment: 3D view from top
#  type: render_3d
#  dir: +/3D
#  options:
#    ray_tracing: true
#    orthographic: true
#- name: basic_render_3d_30deg
#  comment: 3D view from 30 degrees
#  type: render_3d
#  dir: +/3D
#  output_id: 30deg
#  options:
#    ray_tracing: true
#    rotate_x: 3
#    rotate_z: -2
#- name: basic_render_3d_bottom
#  comment: 3D view from bottom
#  type: render_3d
#  dir: +/3D
#  options:
#    ray_tracing: true
#    orthographic: true
#    view: bottom
...
definitions:
  _KIBOT_MANF_DIR_COMP: +/Manufacturers
  _KIBOT_GERBER_LAYERS: "- layer: 'F.Cu'\n        suffix: 'F_Cu'\n        description:\
    \ 'Front copper'\n      - layer: 'In1.Cu'\n        suffix: 'In1_Cu'\n        description:\
    \ 'Inner layer 1'\n      - layer: 'In2.Cu'\n        suffix: 'In2_Cu'\n       \
    \ description: 'Inner layer 2'\n      - layer: 'B.Cu'\n        suffix: 'B_Cu'\n\
    \        description: 'Bottom copper'\n      - layer: 'B.Silkscreen'\n       \
    \ suffix: 'B_Silkscreen'\n        description: 'Bottom silkscreen (artwork)'\n\
    \      - layer: 'F.Silkscreen'\n        suffix: 'F_Silkscreen'\n        description:\
    \ 'Front silkscreen (artwork)'\n      - layer: 'B.Mask'\n        suffix: 'B_Mask'\n\
    \        description: 'Bottom soldermask (negative)'\n      - layer: 'F.Mask'\n\
    \        suffix: 'F_Mask'\n        description: 'Front soldermask (negative)'\n\
    \      - layer: 'Edge.Cuts'\n        suffix: 'Edge_Cuts'\n        description:\
    \ 'Board shape'"
